[package]
name = "khel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
bytemuck = { version = "1.16.0", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.21"
pollster = "0.3.0"
wgpu = "0.20.0"
winit = "0.30.0"
